server:
  host: ${SERVER_HOST}
  port: ${SERVER_PORT}
  tls:
    mode: ${SERVER_TLS_MODE}
    ca: ${SERVER_TLS_CA}
    cert: ${SERVER_TLS_CERT}
    key: ${SERVER_TLS_KEY}

database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  user: ${DATABASE_USER}
  pass: ${DATABASE_PASS}
  name: ${DATABASE_NAME}

coin:
  xmr:
    daemon:
      url: ${XMR_DAEMON_URL}
      user: ${XMR_DAEMON_USER}
      pass: ${XMR_DAEMON_PASS}
